In [ ]:
# default_exp em

In [ ]:
# export
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import scipy.stats as ss
from easydict import EasyDict
from scipy.spatial.distance import cdist
from sklearn.metrics import roc_auc_score,adjusted_mutual_info_score, adjusted_rand_score
from tqdm.notebook import tqdm

## **Bag$_i$**


**latent positive class conditional distribution**
* $z_k = 1$ indicates instance came from component k

$p^i(z_k = 1 | y=1) = \pi^i_k$

**latent negative class conditional distribution**

$p^i(z_k=1 | y=0) = \rho^i_k$

**latent positive posterior distribution**

$ p(z_k=1|x, y=1) = \gamma(z_k) = \frac{\pi^i_k \phi^1_k(x;\mu^1_k,\Sigma^1_k)}{\sum_{j=1}^{K_1} \pi^i_j \phi^1_j(x;\mu^1_j,\Sigma^1_j)} $

**Latent Posterior**

I don't think this is right, should be p(y=1|x) not p(y=1)

$ p(z_k=1|x) = p(y=1) p(z_k=1|y=1,x) + p(y=0)p(z_k=1|y=0,x) = \alpha \frac{\pi_k^i \phi^1_k(x)}{\sum_{j=1}^{K_1} \pi_k^j \phi^1_j(x)} + (1-\alpha)\frac{\rho_k^i \phi^0_k(x)}{\sum_{j=1}^{K_0}\rho_j^i \phi^0_j(x)}$

**positive class conditional distribution**
* K-component gaussian mixture model
* components shared across bags
* mixture weights unique to each bag

$p^i(x|y=1) = \sum_{k=1}^{K_1} \pi^i_k \phi^1_k(x;\mu^1_k,\Sigma^1_k)$

**marginal distribution**

$p(x|b_i) = p(y=1|b_i)p(x|y=1,b_i) + p(y=0|b_i)p(x|y=0,b_i)$

$p^i(x) =\alpha_i \sum_{k=1}^{K_1} \pi^i_k \phi^1_k(x;\mu^1_k,\Sigma^1_k) + (1-\alpha_i) \sum_{k=1}^{K_0}\rho^i_k \phi^0_k(x;\mu^0_k;\Sigma^0_k)$

## Bag$_i \cup$ Bag$_j$

$p(x)= w_i [(\alpha_i \sum_{k=1}^{K_1} \pi^i_k \phi^1_k(x;\mu^1_k,\Sigma^1_k) + (1-\alpha_i) \sum_{k=1}^{K_0}\rho^i_k \phi^0_k(x;\mu^0_k;\Sigma^0_k))] + w_j[\alpha_j \sum_{k=1}^{K_1} \pi^j_k \phi^1_k(x;\mu^1_k,\Sigma^1_k) + (1-\alpha_j) \sum_{k=1}^{K_0}\rho^j_k \phi^0_k(x;\mu^0_k;\Sigma^0_k)]$

## Merged Bags
* $b_i := \{c_i,m_i\}$ : bag with component and mixture sample 
* B : set of bags {$b_i$}
* positive bag weight : $w^1_i = \frac{|c_i|}{\sum_{j\in B} |c_j|}$
* unlabeled bag weight : $w_i = \frac{|m_i|}{\sum_{j\in B} |m_j|}$

**Positive Latent Marginal**

$ p(z_k = 1|y=1) = \sum_{i=1}^{|B|} p(b_i)p(z_k=1|b_i,y=1) = \sum_{i=1}^{|B|} w^1_i \pi_k^i = \pi_k^B$

**Positive conditional latent posterior**

$p(z_k=1|x,y=1) = \gamma^B(z_k) = \frac{\pi_k^B \phi_k(x)}{\sum_{j=1}^K \pi_j^B \phi_j(x))}$

**Positive Class Conditional Distribution**

$p(x|y=1) = \sum_{k=1}^{K_1} p(z_k=1 | y=1)p(x|z_k=1,y=1) = \sum_{k=1}^{K_1}(\sum_{i=1}^{|B|} w^1_i \pi^i_k) \phi^1_k(x;\mu^1_k,\Sigma^1_k)$

**Marginal Distribution**

$p(x) = \sum_{k=1}^{K_1} (\sum_{i=1}^{|B|}w_i \alpha_i \pi_k^i) \phi_k^1(x|\mu^1_k,\Sigma^1_k) + \sum_{k=1}^{K_0}(\sum_{i=1}^{|B|}w_i (1-\alpha_i)\rho_k^i)\phi^0_k(x;\mu^0_k,\Sigma^0_k)$

**Negative Class Conditional**

$p(x|y=0) = \sum_{i=1}^{|B|} p(x,b_i|y=0)$

$p(x|y=0) =\sum_{i=1}^{|B|} p(x|b_i,y=0)p(b_i|y=0)$

$p(x|y=0) = \sum_{i=1}^{|B|} p(x|b_i,y=0)\frac{p(y=0|b_i)p(b_i)}{p(y=0)}$

$p(x|y=0) = \sum_{i=1}^{|B|}(\sum_{k=1}^{K} p(x,z_k=1|b_i,y=0))\frac{p(y=0|b_i)p(b_i)}{p(y=0)}$

$p(x|y=0) =  \sum_{i=1}^{|B|}(\sum_{k=1}^{K} p(x|z_k=1, b_i,y=0)p(z_k=1|b_i,y=0))\frac{p(y=0|b_i)p(b_i)}{p(y=0)}$

$p(x|y=0) = \sum_{i=1}^{|B|}(\sum_{k=1}^K \phi_k^0(x)\rho_k^i) \frac{(1-\alpha_i)w_i}{\sum_{i=1}^{|B|}(1-\alpha_i)w_i}$

In [ ]:


# export
def KMeansInit(X, k):
    means = [X[np.random.choice(np.arange(X.shape[0]))]]
    for iteration in range(k-1):
        dists = cdist(X, np.stack(means)).min(1)
        probs = dists / dists.sum()
        nextIndex = np.random.choice(np.arange(X.shape[0]),p=probs)
        means.append(X[nextIndex])
    return np.stack(means)

class EM:
    def __init__(self, X, k):
        self.X = X
        self.k = k
        self.N,self.dim = self.X.shape
        self.initializeComponents()
        
    def initializeComponents(self):
        mins = self.X.min(0)
        maxs = self.X.max(0)
        # USE K-MEANS++
#         self.mus = KMeansInit(self.X, self.k)
        self.mus = self.X[np.random.choice(np.arange(self.X.shape[0]),size=self.k)]
        self.covs = np.stack([np.eye(self.dim) for _ in range(self.k)])
        self.pi = np.random.dirichlet(np.ones(self.k))
        
    def E_Step(self):
        gammas = np.zeros((self.N,self.k))
        for n in range(self.N):
            for k in range(self.k):
                gammas[n,k] = self.pi[k] * ss.multivariate_normal.pdf(self.X[n],
                                                                      mean=self.mus[k],
                                                                      cov=self.covs[k])
            gammas[n] = gammas[n] / gammas[n].sum()
        self.gammas = gammas
        
    def M_Step(self):
        Nk = np.sum(self.gammas, axis=0)[:,np.newaxis]
        self.mus = np.dot(self.gammas.T, self.X) / Nk
        self.pi = np.mean(self.gammas,axis=0)
        for k in range(self.k):
            x = np.matrix(self.X - self.mus[k,:])
            gamma_diag = np.matrix(np.diag(self.gammas[:,k]))
            sigma_k = x.T * gamma_diag * x
            self.covs[k,:,:] = sigma_k / Nk[k]
            
            
    def log_likelihood(self):
        ll = 0
        for xn in self.X:
            ll += np.log(np.sum([pik * ss.multivariate_normal.pdf(xn,
                                                                  mean=muk,
                                                                  cov=covk) for pik,muk,covk in zip(self.pi,
                                                                                                    self.mus,
                                                                                                    self.covs)]))
        return ll

## Experiment Description
Here, I test whether a multi-instance clustering approach can lead to better estimates of the latent cluster assignment than separate clustering processes. While Shantanu and I thought we should compare the resulting mixing proportions, I think comparing the cluster predictions derived from the latent posterior more directly compares the values of interest. I use the [adjusted rand index](https://en.wikipedia.org/wiki/Rand_index) to compare the quality of the clusterings of the two methods.

As seen in the above experiments, the average adjusted rand index across all bags is higher when using the multi-instance clustering approach. Further, the multi-instance method ensures the estimated distributions $\phi_k$ are the same for each bag. I do not evaluate the quality of the resulting distributions and believe the quality of the gaussians degrades in high dimensions.

**Notes**
* I'm not directly comparing the quality of the latent posterior but rather the clustering estimates that those posteriors lead to
* I'm treating this evaluation as an alternative to separately comparing the quality of the latent marginal (r$^i_j$ i.e. p(z = k) ) and the fitted distributions $\phi_k$

In [ ]:
# export
class MultiEM:
    def __init__(self, bags, n_components):
        self.em_instances = []
        self.labels = []
        self.bags = bags
        # Initialize each EM instance
        for bag in self.bags:
            self.em_instances.append(EM(bag.X_pos, n_components))
        # Override the initialization

    def run_positive_em(self, n_iters, multi=True, KMeansPPInit=True):
        if KMeansPPInit:
            if multi:
                for inst in range(len(self.em_instances)):
                    self.em_instances[inst].mus = KMeansInit(np.concatenate([e.X for e in self.em_instances]),
                                                      self.em_instances[0].k)
            else:
                self.em_instances[0].mus = KMeansInit(np.concatenate([e.X for e in self.em_instances]),
                                                      self.em_instances[0].k)
        self.logLikelihoods = np.zeros((len(self.em_instances),
                                        n_iters+2))
        for inst in range(len(self.em_instances)):
            self.logLikelihoods[inst,0] = self.em_instances[inst].log_likelihood()
        for iteration in tqdm(range(1, n_iters+1),total=n_iters,leave=False):
            for inst in range(len(self.em_instances)):
                self.em_instances[inst].E_Step()
                self.em_instances[inst].M_Step()
                if multi:
                    self.em_instances[(inst+1) % len(self.em_instances)].mus = self.em_instances[inst].mus
                    self.em_instances[(inst+1) % len(self.em_instances)].covs = self.em_instances[inst].covs
                self.logLikelihoods[inst,iteration] = self.em_instances[inst].log_likelihood()
        # After final iteration, pass mu and cov to all instances and update gammas through the E_Step
        for j in range(len(self.em_instances)):
            if multi:
                self.em_instances[j].mus = self.em_instances[0].mus
                self.em_instances[j].covs = self.em_instances[0].covs
                # update gamma with new mus and covs values
                self.em_instances[j].E_Step()
            self.logLikelihoods[j, -1] = self.em_instances[j].log_likelihood()
        self.compute_positive_clustering_performance()

    def compute_positive_clustering_performance(self):
        adjusted_rand_scores = []
        for em,bag in zip(self.em_instances, self.bags):
            adjusted_rand_scores.append(adjusted_rand_score(bag.positive_component_labels,
                                                            np.argmax(em.gammas,axis=1)))
        self.score = np.mean(adjusted_rand_scores)

    def cluster_unlabeled(self):
        for bagnum, (bag, em) in enumerate(zip(self.bags, self.em_instances)):
            assignments = np.zeros(bag.x_unlabeled.shape[0]).astype(int)
            for instnum,inst in enumerate(bag.x_unlabeled):
                lls = np.zeros(em.k)
                for i,(mu,cov) in enumerate(zip(em.mus, em.covs)):
                    lls[i] = ss.multivariate_normal.logpdf(inst,mean=mu,cov=cov)
                assignments[instnum] = np.argmax(lls)
            self.bags[bagnum].unlabeled_assignments = assignments

In [ ]:
# export
def generateBags(NBags,
                 NPos=200,
                 NUnlabeled=1000,
                 pos_means=[[2,2], [-2,-2], [2,-2]],
                 neg_means=[[0,0]],
                 pos_covs=[np.eye(2)]*3,
                 neg_covs=[np.eye(2)]):
    bags = []
    K = len(pos_means)
    D = len(pos_means[0])
    for _ in tqdm(range(NBags)):
        bag = EasyDict()
        bag.alpha = np.random.uniform()
        bag.pi = np.random.dirichlet(np.ones(K)*1.5)
        bag.rho = np.random.dirichlet(np.ones(K)*1.5)
        bag.gamma = bag.alpha * bag.pi + (1 - bag.alpha) * bag.rho
        bag.eta = bag.alpha * bag.pi / bag.gamma
        bag.posClusterAssignment = np.random.choice(np.arange(K), p=bag.pi.ravel(),size=NPos)
        bag.unlabeledPosClusterAssignment = np.random.choice(np.arange(K),
                                                         p=bag.pi.ravel(),
                                                         size=np.round(NUnlabeled * bag.alpha).astype(int))
        upLabels, upCounts = np.unique(bag.unlabeledPosClusterAssignment,return_counts=True)
        bag.empiricalPi = np.zeros(K)
        for label,count in zip(upLabels,upCounts):
            bag.empiricalPi[label] = count / upCounts.sum()
        bag.unlabeledNegClusterAssignment = np.random.choice(np.arange(K),
                                                         p=bag.rho.ravel(),
                                                         size=np.round(NUnlabeled * (1 - bag.alpha)).astype(int))
        unLabels, unCounts = np.unique(bag.unlabeledNegClusterAssignment,return_counts=True)
        bag.empiricalRho = np.zeros(K)
        for label,count in zip(unLabels,unCounts):
            bag.empiricalRho[label] = count / unCounts.sum()
        bag.empiricalGamma = bag.alpha * bag.empiricalPi + (1-bag.alpha) * bag.empiricalRho
        bag.empiricalEta = bag.alpha * bag.empiricalPi / bag.empiricalGamma
        bag.X_pos = np.zeros((0,D))
        bag.hiddenLabels = np.concatenate((np.ones_like(bag.unlabeledPosClusterAssignment),
                                           np.zeros_like(bag.unlabeledNegClusterAssignment)))
        bag.x_unlabeled = np.zeros((0,D))
        # sample positive data
        for ci in tqdm(bag.posClusterAssignment,leave=False):
            xi = np.random.multivariate_normal(pos_means[ci], pos_covs[ci])[None]
            bag.X_pos = np.concatenate((bag.X_pos,xi))
        
        # sample unlabeled pos data
        for ci in tqdm(bag.unlabeledPosClusterAssignment,leave=False):
            xi = np.random.multivariate_normal(pos_means[ci], pos_covs[ci])[None]
            bag.x_unlabeled = np.concatenate((bag.x_unlabeled, xi))
        # sample unlabeled neg data
        for ci in tqdm(bag.unlabeledNegClusterAssignment,leave=False):
            xi = np.random.multivariate_normal(neg_means[ci], neg_covs[ci])[None]
            bag.x_unlabeled = np.concatenate((bag.x_unlabeled, xi))
        bags.append(bag)
    return bags

In [ ]:
bags = generateBags(1,
                    NPos=1000,
                    NUnlabeled=1000,
                    neg_means=[[0,0],[-1,-1],[-2,-2]],
                    neg_covs = [np.eye(2)]*3)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1000 [00:00<?, ?it/s]

  0%|          | 0/434 [00:00<?, ?it/s]

  0%|          | 0/566 [00:00<?, ?it/s]

In [ ]:
bags[0].pi

array([0.23422853, 0.51923463, 0.24653684])

In [ ]:
bags[0].empiricalPi

array([0.23087432, 0.53005464, 0.23907104])

In [ ]:
bags[0].empiricalGamma

array([0.27997281, 0.45604099, 0.2639862 ])

In [ ]:
bags[0].gamma

array([0.28781205, 0.44668068, 0.26550727])

In [ ]:
bags[0].eta

array([0.05781562, 0.12358583, 0.03358507])

In [ ]:
bags[0].empiricalEta

array([0.06773035, 0.150059  , 0.02100531])

In [ ]:
bags = generateBags(100,NPos=200)

In [ ]:
mem = MultiEM(bags,3)

In [ ]:
mem.run_positive_em(10, multi=True, KMeansPPInit=True)

In [ ]:
aes = []
bce = []
for em, bag in zip(mem.em_instances, mem.bags):
    aes.append(np.abs(em.pi - bag.pi))
    bce.append(np.sum(-1 * bag.pi * np.log(em.pi)))
print("pi_k MAE: {:.3f}\nBCE: {:.3f}".format(np.mean(aes), np.mean(bce)))

In [ ]:
mem.score

In [ ]:
mem2 = MultiEM(bags,3)

In [ ]:
mem2.run_positive_em(10, multi=False,KMeansPPInit=True)

In [ ]:
aes2 = []
bce2= []
for em, bag in zip(mem2.em_instances, mem2.bags):
    aes2.append(np.abs(em.pi - bag.pi))
    bce2.append(np.sum(-1 * bag.pi * np.log(em.pi)))
print("pi_k MAE: {:.3f}\nBCE: {:.3f}".format(np.mean(aes2), np.mean(bce2)))

In [ ]:
mem2.score

In [ ]:
mem3 = MultiEM(bags,3)
mem3.run_positive_em(10,multi=True,KMeansPPInit=False)
aes3 = []
bce3= []
for em, bag in zip(mem3.em_instances, mem3.bags):
    aes3.append(np.abs(em.pi - bag.pi))
    bce3.append(np.sum(-1 * bag.pi * np.log(em.pi)))
print("pi_k MAE: {:.3f}\nBCE: {:.3f}".format(np.mean(aes3), np.mean(bce3)))

In [ ]:
mem3.score

In [ ]:
mem4 = MultiEM(bags,3)
mem4.run_positive_em(10,multi=False,KMeansPPInit=False)
aes4 = []
bce4= []
for em, bag in zip(mem4.em_instances, mem4.bags):
    aes4.append(np.abs(em.pi - bag.pi))
    bce4.append(np.sum(-1 * bag.pi * np.log(em.pi)))
print("pi_k MAE: {:.3f}\nBCE: {:.3f}".format(np.mean(aes4), np.mean(bce4)))

In [ ]:
mem4.score

In [ ]:
for l in mem.logLikelihoods:
    plt.plot(l)

In [ ]:
for l in mem2.logLikelihoods:
    plt.plot(l)

In [ ]:
fig,ax = plt.subplots(1,len(mem.bags[:10]),figsize=(4 * len(mem.bags[:10]),4),sharey=True, sharex=True)
for ds_num in range(len(mem.bags[:10])):
    for comp in range(mem.em_instances[ds_num].k):
        lambda_, v = np.linalg.eig(mem.em_instances[ds_num].covs[comp])
        lambda_ = np.sqrt(lambda_)

        ell = matplotlib.patches.Ellipse(xy=mem.em_instances[ds_num].mus[comp],
                          width=lambda_[0]*2*2, height=lambda_[1]*2*2,
                          angle=np.rad2deg(np.arccos(v[0, 0])),alpha=.5)
        ax[ds_num].add_artist(ell)
        # separate
        lambda_, v = np.linalg.eig(mem2.em_instances[ds_num].covs[comp])
        lambda_ = np.sqrt(lambda_)

        ell = matplotlib.patches.Ellipse(xy=mem2.em_instances[ds_num].mus[comp],
                          width=lambda_[0]*2*2, height=lambda_[1]*2*2,
                          angle=np.rad2deg(np.arccos(v[0, 0])),alpha=.25,color="red")
        ax[ds_num].add_artist(ell)
        # done
    ax[ds_num].scatter(mem.bags[ds_num].X_pos[:,0],
                       mem.bags[ds_num].X_pos[:,1],alpha=.5,color="green")
plt.show()

Mutl-EM with KMeans++:
* MAE: 0.009
* BCE: 1.033
* clustering score: 0.9199

Separate-EM with KMeans++
* MAE: 0.145
* BCE: 1.232
* clustering score: 0.71

Multi-EM without KMeans++
* MAE: 0.167
* BCE: 1.241
* clustering score: 0.9199

Separate-EM without KMeans++:
* MAE: 0.145
* BCE: 1.228
* clustering score: 0.6708 (edited) 